### PR TITLE
Update documentation: passwords will be cleared

### LINKED ISSUE #3: Why unset password variables?
https://github.com/Azure/go-pkcs12/blob/master/crypto.go#L61
https://github.com/Azure/go-pkcs12/blob/master/pkcs12.go#L77

Why are the password variables unset?
This looks like a useless action to me, the old data isn't removed from memory because they're still being referred to from outside the function. And even if they weren't, it would require GC to totally clean them from memory..

If you want the functions to clear the passwords from memory: use `[]byte` in both cases and add a `for range` setting each byte to `0x00` or something random.

### PR DESCRIPTION
**Pull request by paulmey**
Fixes #3

### CODE REVIEW

**Comment by paulmey** [comment]
@dgryski is this what you meant?

**Comment by dgryski** [comment]
Yes, if we're overwriting an input parameter, the docs should make this clear.

(Note that I'm still not convinced we should be zeroing out the password...)

**Comment by nathany** [comment]
I think it would be better to leave that responsibility with the caller as with x509.DecryptPEMBlock.

**Comment by ahmetalpbalkan** [comment]
@paulmey keep or close this PR?

**Comment by nathany** [comment]
Depends on #3, but right now this is the case so having documentation that matches makes sense.

**Comment by paulmey** [comment]
@ahmetalpbalkan I put you on point to decide #3 and hence whether to merge this or revert the bits of code that clear the password arrays

**Comment by paulmey** [comment]
closing in favor of #21

**Pull request closed without merging**
