### PR TITLE
golint fixes

### PR DESCRIPTION
**Pull request by nathany**
* rename Id to ID

### CODE REVIEW

**Comment by nathany** [comment]
I'm less sure about the lint error for don't use underscores in Go names (in this particular case). Especially since this lint error occurs many, many times in the Go standard library.

```
crypto.go:16:2: don't use underscores in Go names; const pbeWithSHAAnd3_KeyTripleDES_CBC should be pbeWithSHAAnd3KeyTripleDESCBC
crypto.go:17:2: don't use underscores in Go names; const pbewithSHAAnd40BitRC2_CBC should be pbewithSHAAnd40BitRC2CBC
```

**Comment by ahmetalpbalkan** [comment]
if those are the only ones left I guess we can remove underscores as and probably use shorter names with more comments. Most of the underscores in go stdlib come from syscall package where the constants are generated from OS APIs, there could be probably others.

**Comment by nathany** [comment]
So just go with pbeWithSHAAnd3KeyTripleDESCBC as it suggests?

**Comment by ahmetalpbalkan** [comment]
I'll let @paulmey decide.

**Comment by paulmey** [comment]
@nathany @ahmetalpbalkan let's just take the suggestions. These names came pretty much directly from RFC's/ASN.1 specs, I have no emotional bond with them. :smile:

**Comment by nathany** [comment]
Okay. Lint free.

**Comment by ahmetalpbalkan** [comment]
LGTM.

**Comment by paulmey** [comment]
Thanks @nathany

**Pull request merged**
